backend:
  name: github
  repo: YuriiHaiduk/AI-TEST
  branch: main
  base_url: https://ai-barbershop-yurii.vercel.app
  auth_endpoint: api/auth

media_folder: "images"       # Куда сохранять загруженные клиентом картинки
public_folder: "/images"

collections:
  - name: "settings"
    label: "Информация на сайте"
    files:
      - file: "site-data.json" # Файл, где будут храниться тексты
        label: "Контакты и Заголовки"
        name: "contacts"
        fields:
          - { label: "Заголовок сайта", name: "title", widget: "string" }
          - { label: "Телефон", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }