backend:
  name: github
  repo: YuriiHaiduk/AI-TEST
  branch: main
  base_url: https://ai-barbershop-yurii.vercel.app
  auth_endpoint: api/auth

media_folder: "images"       # Куда сохранять загруженные клиентом картинки
public_folder: "/images"

collections:
  - name: "settings"
    label: "Информация на сайте"
    files:
      - file: "site-data.json" # Файл, где будут храниться тексты
        label: "Контакты и Заголовки"
        name: "contacts"
        fields:
          - { label: "Заголовок на главной", name: "hero_title", widget: "string" }
          - { label: "Подзаголовок на главной", name: "hero_subtitle", widget: "text" }
          - { label: "Заголовок 'О нас'", name: "about_title", widget: "string" }
          - { label: "Текст 'О нас'", name: "about_text", widget: "text" }
          - { label: "Телефон", name: "phone", widget: "string" }
          - { label: "E-Mail", name: "email", widget: "string" }
          - { label: "Адрес", name: "address", widget: "string" }